import React, { useState, useRef } from 'react';
import { Camera, Upload, Loader2, Check, AlertCircle, RefreshCw, X } from 'lucide-react';
import { analyzeClassroomImage } from '../../services/geminiService';
import { GeminiAnalysisResponse, Student, UserRole } from '../../types';
import { MockDataService } from '../../services/mockStore';

export const TakeAttendance: React.FC = () => {
  const [step, setStep] = useState<'upload' | 'processing' | 'result'>('upload');
  const [image, setImage] = useState<string | null>(null);
  const [analysis, setAnalysis] = useState<GeminiAnalysisResponse | null>(null);
  const [identifiedStudents, setIdentifiedStudents] = useState<Student[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Mock student mapping based on AI count
  const mapStudentsToCount = async (count: number) => {
    const allStudents = await MockDataService.getStudents();
    // Simulate identification logic: just take first N students + random absent ones
    // In real app, this would use facial embeddings.
    const present = allStudents.slice(0, Math.min(count, allStudents.length));
    return present;
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setImage(reader.result as string);
        setError(null);
      };
      reader.readAsDataURL(file);
    }
  };

  const processImage = async () => {
    if (!image) return;
    setStep('processing');
    setError(null);
    try {
      const base64Data = image.split(',')[1];
      const mimeType = image.split(';')[0].split(':')[1];
      
      const result = await analyzeClassroomImage(base64Data, mimeType);
      
      if (result.confidence < 20) {
        throw new Error("Image unclear or no students detected. Please try again.");
      }

      setAnalysis(result);
      const students = await mapStudentsToCount(result.count);
      setIdentifiedStudents(students);
      setStep('result');

    } catch (err: any) {
      setError(err.message || "Failed to process image.");
      setStep('upload');
    }
  };

  const reset = () => {
    setImage(null);
    setAnalysis(null);
    setIdentifiedStudents([]);
    setStep('upload');
  };

  const handleSave = async () => {
      if (!analysis) return;
      setIsSaving(true);
      try {
          // Calculate stats
          const allStudents = await MockDataService.getStudents();
          const totalStudents = allStudents.length;
          const presentCount = identifiedStudents.length;
          const absentCount = totalStudents - presentCount;

          await MockDataService.saveSession({
              id: '', // Will be generated by DB
              date: new Date().toISOString(),
              className: "Class " + new Date().toLocaleDateString(), // Placeholder
              totalStudents,
              presentCount,
              absentCount,
              status: 'COMPLETED',
              aiAnalysis: {
                  ...analysis,
                  studentCount: presentCount,
                  detectedStudents: identifiedStudents.map(s => s.id)
              }
          }, identifiedStudents.map(s => s.id));

          alert("Attendance data saved to database successfully!");
          window.location.hash = 'teacher/dashboard';
      } catch (err: any) {
          setError(err.message || "Failed to save attendance.");
          setIsSaving(false);
      }
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
        <div>
            <h1 className="text-2xl font-bold text-slate-900">Take Attendance</h1>
            <p className="text-slate-500">Capture a photo to mark attendance automatically.</p>
        </div>

      {/* Step 1: Upload */}
      {step === 'upload' && (
        <div className="bg-white rounded-xl border border-slate-200 p-8 text-center shadow-sm">
          {!image ? (
            <div 
                className="border-2 border-dashed border-slate-300 rounded-xl p-12 flex flex-col items-center justify-center hover:bg-slate-50 transition-colors cursor-pointer"
                onClick={() => fileInputRef.current?.click()}
            >
              <div className="bg-blue-100 p-4 rounded-full mb-4">
                <Camera className="w-8 h-8 text-blue-600" />
              </div>
              <h3 className="text-lg font-bold text-slate-900 mb-2">Upload Class Photo</h3>
              <p className="text-slate-500 mb-6 max-w-sm mx-auto">Click to browse or take a photo using your device camera.</p>
              <button className="bg-blue-600 text-white px-6 py-2.5 rounded-lg hover:bg-blue-700 font-medium transition-colors">
                Select Photo
              </button>
              <input 
                ref={fileInputRef}
                type="file" 
                accept="image/*" 
                className="hidden" 
                onChange={handleImageUpload} 
              />
            </div>
          ) : (
            <div className="space-y-6">
                <div className="relative rounded-xl overflow-hidden max-h-[500px] inline-block shadow-lg">
                    <img src={image} alt="Classroom" className="w-full h-full object-contain" />
                    <button 
                        onClick={() => setImage(null)}
                        className="absolute top-2 right-2 bg-white/90 p-2 rounded-full text-slate-700 hover:text-red-600 shadow-sm"
                    >
                        <X className="w-5 h-5" />
                    </button>
                </div>
                
                {error && (
                    <div className="bg-red-50 text-red-600 p-3 rounded-lg flex items-center justify-center space-x-2">
                        <AlertCircle className="w-5 h-5" />
                        <span>{error}</span>
                    </div>
                )}

                <div className="flex justify-center space-x-4">
                    <button 
                        onClick={() => setImage(null)}
                        className="px-6 py-2.5 border border-slate-300 rounded-lg font-medium text-slate-700 hover:bg-slate-50"
                    >
                        Retake
                    </button>
                    <button 
                        onClick={processImage}
                        className="px-6 py-2.5 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700 shadow-md flex items-center"
                    >
                        <RefreshCw className="w-4 h-4 mr-2" />
                        Process Attendance
                    </button>
                </div>
            </div>
          )}
        </div>
      )}

      {/* Step 2: Processing */}
      {step === 'processing' && (
        <div className="bg-white rounded-xl border border-slate-200 p-16 text-center shadow-sm flex flex-col items-center">
            <Loader2 className="w-12 h-12 text-blue-600 animate-spin mb-4" />
            <h3 className="text-xl font-bold text-slate-900 mb-2">Analyzing Image...</h3>
            <p className="text-slate-500 max-w-md">Our AI is detecting students and verifying the environment. This usually takes a few seconds.</p>
        </div>
      )}

      {/* Step 3: Result */}
      {step === 'result' && analysis && (
        <div className="space-y-6">
            {error && (
                <div className="bg-red-50 text-red-600 p-3 rounded-lg flex items-center justify-center space-x-2">
                    <AlertCircle className="w-5 h-5" />
                    <span>{error}</span>
                </div>
            )}
            
            {/* AI Summary Card */}
            <div className="bg-white rounded-xl border border-slate-200 overflow-hidden shadow-sm">
                <div className="bg-gradient-to-r from-blue-600 to-indigo-600 p-6 text-white">
                    <div className="flex justify-between items-start">
                        <div>
                            <h2 className="text-2xl font-bold mb-1">Attendance Summary</h2>
                            <p className="text-blue-100">{analysis.description}</p>
                        </div>
                        <div className="text-right">
                             <div className="text-3xl font-bold">{identifiedStudents.length}</div>
                             <div className="text-sm text-blue-100">Students Present</div>
                        </div>
                    </div>
                </div>
                <div className="p-4 bg-blue-50 border-b border-blue-100 flex items-center justify-between text-sm">
                    <span className="text-blue-800 font-medium">AI Confidence: {analysis.confidence}%</span>
                    <span className="text-blue-800 font-medium">Classroom Valid: {analysis.isClassroom ? 'Yes' : 'Uncertain'}</span>
                </div>
            </div>

            {/* Student List Grid */}
            <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
                <h3 className="text-lg font-bold text-slate-900 mb-4 flex items-center">
                    <Check className="w-5 h-5 text-green-500 mr-2" />
                    Identified Students
                </h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
                    {identifiedStudents.map(student => (
                        <div key={student.id} className="flex items-center space-x-3 p-3 rounded-lg border border-slate-100 hover:border-blue-200 hover:bg-blue-50 transition-all">
                            <img src={student.avatarUrl} alt={student.name} className="w-10 h-10 rounded-full bg-slate-200" />
                            <div>
                                <p className="font-medium text-slate-900 text-sm">{student.name}</p>
                                <p className="text-xs text-slate-500">{student.usn}</p>
                            </div>
                            <div className="ml-auto">
                                <span className="bg-green-100 text-green-700 text-[10px] px-2 py-1 rounded-full font-bold">Present</span>
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            <div className="flex justify-between pt-4">
                 <button 
                    onClick={reset}
                    disabled={isSaving}
                    className="px-6 py-3 border border-slate-300 rounded-xl font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50"
                >
                    Discard & Retake
                </button>
                <button 
                    onClick={handleSave}
                    disabled={isSaving}
                    className="px-8 py-3 bg-green-600 text-white rounded-xl font-medium hover:bg-green-700 shadow-md shadow-green-200 flex items-center disabled:opacity-50"
                >
                    {isSaving && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                    Confirm & Save Attendance
                </button>
            </div>
        </div>
      )}
    </div>
  );
};